version: '3'

services:
  # Our simple Python service to test the environment
  logger:
    build:
      context: ./src/services/logger
    volumes:
      - ./src/services/logger:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - LOG_LEVEL=INFO